---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewSpringBootRestService"
  group: "atomist"
  artifact: "spring-rugs"
  version: "0.12.0"
  origin:
    repo: "https://github.com/atomist/spring-rugs.git"
    branch: "6b9204311de6e06c390e9feddbeb413f57fa32c4"
    sha: "6b92043"
  parameters:
    - "artifactId": "spring-rest-seed"
    - "groupId": "com.atomist.seeds"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "RestService for creating Spring REST services"
    - "rootPackage": "com.atomist.springteam"
    - "serviceClassName": "RestService"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170608065255"
editor:
  name: "PrepareTravisBuildFiles"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "1.12.0"
  parameters:
    - "project": "lizardspit"
    - "encryptedGithubToken": "I**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "n**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "l**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170609011313"
editor:
  name: "DependencyVersionChangeEditor"
  group: "satellite-of-love"
  artifact: "spring-team-handlers"
  version: "0.3.13"
  parameters:
    - "group": "com.jessitron"
    - "artifact": "survey-source"
    - "desiredVersion": "0.3.2"

