dist: trusty
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
install: true
script: docker login -u $ATOMIST_REPO_USER -p $ATOMIST_REPO_TOKEN $ATOMIST_DOCKER_REGISTRY
  && bash src/main/scripts/travis-build.bash
env:
  global:
  - secure: ngsihlEVy3W9jNQy2h9SwC9B1tJ+wB2684SJuLZ2CQfVJ9lFwdAsIIZcFCTvPOirGUGr9rL6lullPK1P7Gp3VVOFaRoCR5VR9TguBHhDrnB/lcCdtTm4Eapuztnr1X35LXJQYbH1LRuX5WVA4c11Dpm/cmAWBQDcdjJ3MFgMqS+GUrhmESqJnQOkrYk3QU3pq/V2IGQisahcG/GjFGmkxwA/zIYqanueSUDmusB1CsaUm3/Jzfi4r8j67m5v4t78OTVCn/8bO4woz/vVr1GaSoEAlJLcOhncqOE2EKkOjVkzVyyOKhPUif0BLXyhseKx2GW0RE1UBa9DNIYBeBjOTYBOmKZN7xKpsLHYkk7JUECo0t0zUyik+R7YWojnlYcKPWvMls8oEbeafxmjm+qIFwKGXD1HifV/Jq9CU4IWe2dpMxiFPWsnhCBRbn8zbOuXzpy5E5C7Anr74BHMPUefOpz9RoJakwcxOX6reYXg2D26GZAkFwxsCAk0n14tNGvRUUHbAr2vgC0rRkHaa0jcutIHe4UP8FY8anZ8/hs83NE7av9dmDSaJVSUH5Dzdw8HfhOxJyr2r94ZbFODplvMCVUsDMksiDCagC5/eO7+5qhot7ZZQ+0x9vYiZKk29OfH/rMYpMMR2CQWnFKmiWqF4QuhR4DK5RQGg7V9yfSiDWE=
  - secure: lhhsdTeHRgWT/gicME0eRrZ+sUeT0aPNMkQfGTszU0gBNgV2Pylo0VfbcHZ7WbA8scfSLXkn67lKr59KrjzuOkm1fjwjZ5yjMU477/ELL18nxvgAfNQ7uY7ppXD3wAKQgKWG3PsyMK2oGMRUFiHKmw+cnZ1vM89YXFipzq5qmEgLr9p+18QOvEc33JmhzSWYoyAm66AXnH7a9XlOXtvY/3XmUYyodADKLcRMyF/rX4nQDtEULY1fMJS//tCarof9RohfMYFBfdokbjeuv5r7K7irw6uNc2NouRIZMAXOoTJ+YVwutDJmIFT+vsNYpO/nQuyZJdL/z7E3J6lYlHWw8FGtZyDULLc8tu2KXVJco+gV3XVpDFtqa7i9O+7EBPpVfD739/1XrXLtKGGKpGkZ+bU5C3DjL2F0GescKHS9QpGUYnt5F5xjiz+orRqAckU+4Iwf+PFAiLSSZ1wCtoDHw5xb4DMdNS1S+GEqCPDp1HKfIx5eRvpeZdB8LXRW2YoxptvB3KZbtFTJyp+K1Djj65LQ4ccpih3yKn0WseR31lTQIzOmNimu+HhZQ7RSjCRiFQOib4L1l6e9y7kKHyRo4rIQv+Y1rbfEEUveNq1SIvIH1E5P5fcg9EZRwwu6/Tdx4zMAwH3pM0+LF0C7NzbpYcoXOA7gTl6DNcKuxEToGbU=
  - secure: INE3Rf3NoOIBl9NoXCtXKzlvCw6IQBuDiCVfgQBx+dgxF+/EcQOmUwrn/PeoMsvYjJTLAoUHtOaxswk4GLbSRVaQ83mMPGnEwttSz4ZfM9ljpYvUiiXhrnQK11uXh3GsKEWmmvnRKVHq/R17ay/IHfBuumgQBnO6O+GV2BnYubNw42Tc/cEYEqiP05zJuQLqfhWRc4Q+za+qaEhEINTpSCzTLJ+ZApQtc0YH6fEH8K/obqkMxenfutio7xaLVe3lUj6mNAjDyfRjstEAFI0XMnEweDTCjN/RILsHdfhH/DdBqK9ogf3zT/jbhUaDo8UQ3OnxayvzpteDkWQVtoxNI6VH9IBVDhMjADhyYnTvkL1dN2Ew2CESdgm+jLChI99eRXGgYJkB0OSnZt42z9/ECaAp/kPVa1sJn0+LZADtEwii4F1qMBW0IWw8CFOIJkKeNA7XdzsoC8TpAiuug0EAob9xuoF+B7u1+5brUSbGS7fy3c11YAt/dBHsORQRuqhhLISIOPUaq3WI00P49ql77YNrwjlDyVSr8gpSMB6L5/69ceK7gUxAsg7zuFGbnSnV/QDKv5cB5Nt6OZL60innO/PK/zxNz5vCobkf3c9L8cRI0RgV5IgoU1f1sndIQQuPSS8SWu6RR00jjvkI6h5wk5tEjkcUeh3BE10h8QJEjhE=
  - secure: wxh3NNYeeZe6eGU2oM6/hiKrt/UA+URN7OUlw3jnauEYfLtwU7HFnzS+YWcoEqeH/TKLGvAWNxYbAVmmcEjrV6elY6RS+MScveMZhDBAL8hn9eHoIRUSQ7bFk++DbgIm19OfbzDuQ8SOH6zyIAMKGjXlvBEiozgXH+Bz4a9D84a7kVHlgZYc0N6QAFCQ3Yfxw9DWDnq0MdVBFenTQ+6hnzBflfhim8zZ51NDsXSX8TenxHvULK2DE3sDUMDzNdX4LIIJh01U3BjvSb6yCxOyIKoYwz3UrE1oRLZiwif3mDfKaStinAqS5H/bqjY91eA413+NUz/8kpOPxVH/fih6Z8WVCj79H2/6B3JQEFVscI7jOOQmBNxjZl8cobObFa8lk1CFIX8pi3adMNYzXcWOz+Bifmd3udFbeH45Mxvh4tmlE2pfyOgcXj4MyA6Ju56mGsJ3i8JgJCvtb4ymEtZDo35lWohwDoBdgLjYcfx33Y+ItA8X3NXjhG2Jee7Qz7xwaC3WImkiSPXyiBPYqwK0C/Rp334EJiJHQ12SGklXC9Fx14IY0zIioNNQIZA6AGHKLpxwwySfRYYN4HGYatzHBd/5MdQu156Lu6Y6UnJUKpMn0Ay3U+HeX4Sz1p2Zq3A+y2KF6hNXhudsGrHl3ktP2kTRda+gseb8zKgw920nNVM=
  - ATOMIST_DOCKER_REGISTRY=sforzando-docker-dockerv2-local.artifactoryonline.com
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
